### ISSUE TITLE
Package Request: Qv2ray on Raspberry Pi @ armv7

### ISSUE THREAD

**Issue by digiexper** [Qv2ray/Qv2ray#1015]
Need pre-compiled package for arm32 based linux like raspery pi OS. Arm v7 32bit cpu based package to be precisely.

**Comment by U-v-U** [comment]
You may consider: https://snapcraft.io/qv2ray

**Comment by digiexper** [comment]
> You may consider: https://snapcraft.io/qv2ray

Tryed, some error occur and the app can not initiate, lack some dependencies could not be installed or compatable arm version is not found.

**Comment by U-v-U** [comment]
We cannot officially provide ARM-based binaries since it takes nearly 2hour to build.
If the SNAP doens't work, cc @ymshenyu

**Comment by DuckSoft** [comment]
> > You may consider: https://snapcraft.io/qv2ray
> 
> Tryed, some error occur and the app can not initiate, lack some dependencies could not be installed or compatable arm version is not found.

@digiexper We do attach great importance to architecture compatibility. I have succeeded in compiling and running Qv2ray smoothlessly on aarch64 (Raspberry Pi) and mips64el (Loongson) on Debian GNU/Linux. If you encounter "some error" and the app "cannot initiate", please do provide us with the sufficient information to exactly reproduce the problem, so that we can help make Qv2ray better. 

Your precious response is greatly appreciated.

**Comment by digiexper** [comment]
I take a screenshot of the error message.
[
![Screenshot from 2020-10-06 22-31-16](https://user-images.githubusercontent.com/72401255/95216305-85cac480-07b7-11eb-8da4-a6a38b581af3.png)
](url)

**Comment by DuckSoft** [comment]
@ymshenyu please have a review on this error message.

**Comment by ymshenyu** [comment]
> IIRC raspbian re-compiles debians armhf architecture for ARMv6 (without actually renaming the architecture itself) …
Ubuntu uses ARMv7 for the armhf architecture, so the core snap (coming from ubuntu) that is your runtime env for snaps is incompatible with the binary runtimes of the host system …
try installing an actual debian armhf image instead of raspbian, that should overcome this architectural mess …

For more information, see https://forum.snapcraft.io/t/raspberry-pi-3b-raspian-stretch-snap-not-working/3947

**Comment by DuckSoft** [comment]
Uh, oh. It seems that Raspberry Pi OS have done some black magic and it's actually EXPECTED to be not compatible with Snapcraft applications. The awesome Debian GNU/Linux awaits you.
