### ISSUE TITLE
Question: <On Fedora33 Configuration disappears after shutdown or reboot>

### ISSUE THREAD

**Issue by ByteAKA8bit** [Qv2ray/Qv2ray#1074]
Version: 2.6.3:5840
When First time add a subscription and connect, shutdown or reboot system if not close the App, the added subscription will disappeared.
And if quit the app before shutdown or reboot, subscription will be saved. Maybe we can in time to save the subscription info when it added.

**Comment by DuckSoft** [comment]
@ByteAKA8bit You should provide with us your base information, which, at least includes: your Desktop Environment / Window Manager; using Xorg or Wayland; and all that thing in our template you have just deleted. This issue should have been closed directly since you didn't follow our issue template, but I will forgive that if you add sufficient information for us to repeat the problem.

**Comment by ByteAKA8bit** [comment]
Version: 2.6.3:5840
Desktop Environment: Fedora 33 gnome 3.38.1
Window Manager: Wayland

> When First time add a subscription and connect, shutdown or reboot system if not close the App, the added subscription will disappeared.
> And if quit the app before shutdown or reboot, subscription will be saved. Maybe we can save the subscription info immediately when it added.

就是个小问题,我怀疑是添加订阅时不及时保存,软件退出时才保存本次运行添加的配置文件.在这反馈是因为Telegram用户组验证问题我不太擅长,三次没加进去.要不我把这个问题关了吧...

**Comment by DuckSoft** [comment]
@ByteAKA8bit We’ve noticed something unusual on Wayland sessions, where they simply disconnect Wayland connection from all existing applications. Then Qt will complain about this and trigger an immediate trap signal, stopping the whole program. 

We haven’t found any effective measures to handle this exception. Sadly, for Wayland users, keep in mind that, please do save your settings before shutdown / logoff.
