### ISSUE TITLE
native integration of transparent proxies

### ISSUE THREAD

**Issue by poscat0x04** [Qv2ray/Qv2ray#296]
Setting up transparent proxies are mechanical and can be automated. This can be done by calling nftables/iptables on Linux, netsh on Windows and PF on macOS. It would be great if you can incorporate this feature into qv2ray.

**Comment by DuckSoft** [comment]
Sure. It would be grateful if we can work together.

**Comment by poscat0x04** [comment]
Glad to hear that ^^

**Comment by DuckSoft** [comment]
> Glad to hear that ^^

Consider joining us at Qv2ray User Group (https://t.me/qv2ray) on Telegram.

**Comment by Qv2ray-dev** [comment]
https://github.com/springzfx/cgproxy

**Comment by Qv2ray-dev** [comment]
> https://github.com/springzfx/cgproxy

This project provides good tproxy performance and has been tested using Qv2ray tproxy inbound settings.

Please try that tool. We may consider making a plugin so that users could benefit directly from Qv2ray

For now, I'll close the issue, please feel free to join our user group at: https://t.me/qv2ray
