### ISSUE TITLE
Cannot load translation for en-US, English is now used.

### ISSUE THREAD

**Issue by lunafe** [Qv2ray/Qv2ray#323]
**Briefly describe this bug：**
At the first time opening qv2ray, it shows a warning: `Cannot load translation for en-US, English is now used.`

**How can I trigger this bug：**

open qv2ray on an english version of windows 10 at the first time

**What is expected to happen**

this warning should not shown on an english version of windows 10

**Screenshots**

![01](https://user-images.githubusercontent.com/45958598/74102686-d59db100-4b80-11ea-8e56-8af2bb4782c4.png)

**System Information**

 - OS Type: (Windows 10.0.17763.914)
 - Qv2ray-refs.tags.v2.0.1-win64-gRPC.7z
 - Version: 2.0.1.3100

**Comment by Qv2ray-dev** [comment]
If this is the first time you start Qv2ray, then it's a known issue and has been already fixed: https://github.com/Qv2ray/Qv2ray/issues/298

If not, please tell us how to trigger this problem.

**Comment by DuckSoft** [comment]
Sorry for the inconvenience, but the problem will soon be fixed in coming Qv2ray v2.1.0 release, which is scheduled to be released this week.

You may use the automated build of dev branch from GitHub actions: 
https://github.com/Qv2ray/Qv2ray/actions?query=workflow%3A%22Qv2ray+build+matrix%22+branch%3Adev

Thanks for your reporting.
