### ISSUE TITLE
Win 10 system proxy setting, whats the difference between socks and http?

### ISSUE THREAD

**Issue by bokemanoh** [Qv2ray/Qv2ray#649]
In win 10 system proxy setting, whats the difference between socks and http?
Can I use both At the same time? Will they both be utilized by windows and have different functionalities?

**Comment by DuckSoft** [comment]
Windows supports only HTTP(S) proxy and SOCKS4 proxy. Since using SOCKS4 will leak your DNS queries, we chose to configure Windows to use HTTP inbounds of Qv2ray. However, you may disable the system proxy and configure applications to use its own proxy settings as well. 

You may have a look at our documentation here: 
https://qv2ray.github.io/en/getting-started/step4.html
