### ISSUE TITLE
添加黑名单模式

### ISSUE THREAD

**Issue by Mrneet** [Qv2ray/Qv2ray#666]
希望除了绕过中xx陆外可以增加选项， 比如PAC模式，这样就可以像酸酸和酸酸乳那样只代理某些特定的网址了。毕竟不是所有国外网址都需要。。。

**Comment by DuckSoft** [comment]
黑名单模式将审慎添加。

**Comment by littlef0x** [comment]
I think it's necessary to add an option to set the default behavior, i.e. proxy or direct. In fact there are many foreign websites which are accessible in China. The always-proxy setting now is not friendly for those with limited bandwidth. Moreover, direct connection is required for college students and teachers to access to literature and databases, since the authority is based on IP address.

**Comment by DuckSoft** [comment]
> I think it's necessary to add an option to set the default behavior, i.e. proxy or direct. In fact there are many foreign websites which are accessible in China. The always-proxy setting now is not friendly for those with limited bandwidth. Moreover, direct connection is required for college students and teachers to access to literature and databases, since the authority is based on IP address.

> I think it's necessary to add an option to set the default behavior, i.e. proxy or direct. In fact there are many foreign websites which are accessible in China. The always-proxy setting now is not friendly for those with limited bandwidth.

---


"Blacklist" Mode:
```
(ip, direct) += [0.0.0.0/0, ::1/0]
(domain, direct) += [regexp:.*]
```

---

> Moreover, direct connection is required for college students and teachers to access to literature and databases, since the authority is based on IP address.

```
(domain, direct) += [geosite:category-scholar-!cn]
```
