### ISSUE TITLE
Qv2ray is not opening in MANJARO.

### ISSUE THREAD

**Issue by i-amMasum** [Qv2ray/Qv2ray#667]
**Briefly describe this bug：**
QV2RAY  is not opening in manjaro from today.i am using manjaro 5.6.15-1 kernel

screenshot :
![Screenshot_20200609_112737](https://user-images.githubusercontent.com/54699463/84103022-80957d00-aa44-11ea-82a5-42536c29d158.png)

**Comment by DuckSoft** [comment]
#644

**Comment by DuckSoft** [comment]
Rebuild Qv2ray from AUR may resolve this problem.
```shell
yay -S qv2ray --aur
```

---
If you used some third-party sources special for Arch Linux, you can suffer from a latency between Arch packages and Manjaro packages. Since Manjaro packages is weeks late than Arch packages, in Arch Linux, `protobuf` library is already upgraded. Sources special for Arch Linux may receive Arch Users' complaint about "old dependency", and that's why later you guys come to complain about "too new dependency".

Either give up using a source special for Arch Linux, either give up using Manjaro.
It's up to you.
